"""
Generate the Dataform project in dataform/ from the SQL in sql/ and tests/.

The SQL in sql/ stays the single source of truth (pipeline/run.py runs it
locally or in BigQuery). This script wraps the same queries as Dataform
SQLX files so the pipeline can also live inside BigQuery Studio, where
Dataform shows the dependency graph, runs models in order, and runs the
tests as assertions.

    python pipeline/export_dataform.py

What changes in the conversion:
  - `dataset.table` references become ${ref("table")}, which is how
    Dataform learns the dependency graph.
  - Raw and reference tables (loaded by pipeline/run.py) are declared as
    sources, since Dataform only handles the transformation layer.
  - Each test in tests/ becomes an assertion: a query that must return
    zero rows.
"""

import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "pipeline"))
from run import MODELS, RAW_TABLES, REFERENCE_TABLES  # noqa: E402

OUT = ROOT / "dataform"
PROJECT_ID = "marketing-analytics-pipeline1"
TABLE_REF = re.compile(r"\b(raw|reference|staging|marts)\.([a-z0-9_]+)\b")


def leading_comment(sql):
    """The comment block at the top of a file, as one line of text."""
    lines = []
    for line in sql.splitlines():
        if line.startswith("--"):
            lines.append(line[2:].strip())
        elif line.strip():
            break
    text = " ".join(l for l in lines if l)
    return text.replace("\\", "\\\\").replace('"', '\\"')


def to_sqlx(sql):
    """Swap table references for ${ref()} calls, leaving comments untouched."""
    out = []
    for line in sql.splitlines(keepends=True):
        code, sep, comment = line.partition("--")
        out.append(TABLE_REF.sub(lambda m: '${ref("' + m.group(2) + '")}', code) + sep + comment)
    return "".join(out)


def main():
    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "definitions" / "sources").mkdir(parents=True)

    (OUT / "workflow_settings.yaml").write_text(
        f"""# Generated by pipeline/export_dataform.py
defaultProject: {PROJECT_ID}
defaultLocation: US
defaultDataset: marts
defaultAssertionDataset: assertions
dataformCoreVersion: 3.0.0
""")

    # Sources: tables loaded by pipeline/run.py
    declarations = []
    for table in RAW_TABLES:
        declarations.append(("raw", table))
    for table in REFERENCE_TABLES:
        declarations.append(("reference", table))
    lines = ["// Generated by pipeline/export_dataform.py",
             "// Raw and reference tables are loaded by pipeline/run.py; Dataform reads them.", ""]
    for schema, table in declarations:
        lines.append(f'declare({{ schema: "{schema}", name: "{table}" }});')
    (OUT / "definitions" / "sources" / "sources.js").write_text("\n".join(lines) + "\n")

    # Models
    for dataset, name, path in MODELS:
        sql = path.read_text()
        folder = OUT / "definitions" / dataset
        folder.mkdir(exist_ok=True)
        config = (
            "config {\n"
            '  type: "table",\n'
            f'  schema: "{dataset}",\n'
            f'  description: "{leading_comment(sql)}",\n'
            f'  tags: ["{dataset}"]\n'
            "}\n\n"
        )
        (folder / f"{name}.sqlx").write_text(config + to_sqlx(sql))

    # Tests -> assertions
    folder = OUT / "definitions" / "assertions"
    folder.mkdir()
    for path in sorted((ROOT / "tests").glob("*.sql")):
        sql = path.read_text()
        config = (
            "config {\n"
            '  type: "assertion",\n'
            f'  description: "{leading_comment(sql)}"\n'
            "}\n\n"
        )
        (folder / f"{path.stem}.sqlx").write_text(config + to_sqlx(sql))

    n_models = len(MODELS)
    n_tests = len(list((ROOT / "tests").glob("*.sql")))
    print(f"dataform/: {len(declarations)} sources, {n_models} models, {n_tests} assertions")


if __name__ == "__main__":
    main()
