// Generated by pipeline/export_dataform.py
// Raw and reference tables are loaded by pipeline/run.py; Dataform reads them.

declare({ schema: "raw", name: "clients" });
declare({ schema: "raw", name: "google_ads_campaigns" });
declare({ schema: "raw", name: "meta_ads_campaigns" });
declare({ schema: "raw", name: "shopify_orders" });
declare({ schema: "raw", name: "shopify_refunds" });
declare({ schema: "raw", name: "ga4_sessions" });
declare({ schema: "reference", name: "meta_conversion_actions" });
declare({ schema: "reference", name: "ga4_channel_mapping" });
declare({ schema: "reference", name: "order_exclusions" });
